### ISSUE TITLE
The "options.cwd" property must be of type string. Received type function

### ISSUE THREAD

**Issue by FelixMH** [darkguy2008/parallelshell#69]
I have node 11.0.0 and I have this issue when I use yarn start because a internal command by parallelshell isn't work. I've been use npm-run-all and I've been use the last version of parallelshell and the issue is continue. 

the complete error is : 

**
child_process.js:417
    throw new ERR_INVALID_ARG_TYPE('options.cwd', 'string', options.cwd);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received type function
    at normalizeSpawnArguments (child_process.js:417:11)
    at spawn (child_process.js:532:38)
**

can anybody help me please ?

**Comment by edrcq** [comment]
@FelixMH I hope the PR can help you, dont hesitate to check the commits

-> https://github.com/darkguy2008/parallelshell/pull/70/commits/8d9df713c12cc3fdfc09a9291cdcf6b764bc9e8e

**Comment by FelixMH** [comment]
> @FelixMH I hope the PR can help you, dont hesitate to check the commits
> 
> -> [8d9df71](https://github.com/darkguy2008/parallelshell/commit/8d9df713c12cc3fdfc09a9291cdcf6b764bc9e8e)

Thank you for your comment, I need to solve this, but I am still in the same at the begin of this Open issue, I need help.

**Comment by edrcq** [comment]
Take the content of the file here : 
https://raw.githubusercontent.com/darkguy2008/parallelshell/master/index.js

And put the content in your /project/node_modules/parallelshell/index.js 

It will works in waiting the next release of the module

**Comment by FelixMH** [comment]
You mean that I need to replace the content or just paste it in the file before mencionated?

**Comment by edrcq** [comment]
You take the content of this : (100% copy)
https://raw.githubusercontent.com/darkguy2008/parallelshell/master/index.js

And put in your  /project/node_modules/parallelshell/index.js
(100% paste)

It will works

@FelixMH

**Comment by FelixMH** [comment]
Hi, thanks for the answer. 
now, in this moment I was try put the pasted code and that it works 100% I don't know if then will works fine but in this moment with node 10.0.0 works fine. 

thanks a lot for the answer.

**Comment by juanprog97** [comment]
thanks men,  works 100%

**Comment by armherr66** [comment]
@edrcq 

Thank you very much :)

**Comment by HalfMandu** [comment]
@edrcq it worked, thanks

**Comment by vkuradia** [comment]
Thanks a lot buddy!!! : )

**Comment by rolisanchez** [comment]
Thanks!!

**Comment by mhers91** [comment]
Thank you! this worked perfectly.

**Comment by RichardBradley** [comment]
If anyone else stumbles on this and wants a workaround that doesn't involve locally modifying the node_modules dir, you can do:

    npm -i darkguy2008/parallelshell#8fd83e2 

until a new version is released which includes this fix.

**Comment by ManuelOviedo** [comment]
> npm -i darkguy2008/parallelshell#8fd83e2

its "npm i ..." (without the dash)

**Comment by Melmoth-the-Wanderer** [comment]
Is this going to be fixed/released anytime soon? It's been for almost a yea already and I came across the bug on very first approach to this package.

**Comment by nathan815** [comment]
@FelixMH This issue should be reopened. It is not fixed.

@darkguy2008 Is this going to be released?

**Comment by saurav1423** [comment]
@FelixMH please reopen this issue as the above solution have not worked for me.

**Comment by saurav1423** [comment]
@nathan815 don't try to translate in English, just copy whatever it is and paste it at the told location. It will work 100%.

**Comment by Youvelop** [comment]
Thank you man!

**Comment by Nischalv1999** [comment]
its not working for me, its showing the same error! Can there be any other alternative?

**Comment by omidantilong** [comment]
Can confirm the error still exists. 

The solution posted here still works: https://github.com/darkguy2008/parallelshell/issues/69#issuecomment-438318855

Please get this resolved!

**Comment by tombannister-94** [comment]
I can confirm that this error still exists and the fix [here](https://github.com/darkguy2008/parallelshell/issues/69#issuecomment-438318855) still works: 

Thanks @edrcq for the fix.

**Comment by muhba25** [comment]
Fixed. Thanks @edrcq

**Comment by CamaraMed** [comment]
it works 100%. Thanks a lot

**Comment by Arjungowda1** [comment]
Thanks buddy  :)

**Comment by kaanselhep** [comment]
Yup, I can confirm https://github.com/darkguy2008/parallelshell/issues/69#issuecomment-438318855 this solution works as well... Its very strange but it seems nobody is actually fixing it

**Comment by ssaran2014** [comment]
This problem still exists and the above solution still works. Thank you.

**Comment by pewinski** [comment]
@FelixMH why is this issue closed? I don't think it's fixed in package, just ugly workaround.

**Comment by TIKOsup** [comment]
@edrcq It works! Thank you!

**Comment by nathan815** [comment]
@saurav1423 A workaround isn't a fix. It should be implemented in the package itself and a new version released.

**Comment by SgtPooki** [comment]
@edrcq this is still broken. are you around?

**Comment by SgtPooki** [comment]
for those of you that want this fix to be "permanent".. check out patch-package

**Comment by bajahranks** [comment]
2021 Still not fixed. 

Thankfully [#69](https://github.com/darkguy2008/parallelshell/issues/69#issuecomment-519147261) works....

**Comment by fadiof** [comment]
> You take the content of this : (100% copy) https://raw.githubusercontent.com/darkguy2008/parallelshell/master/index.js
> 
> And put in your /project/node_modules/parallelshell/index.js (100% paste)
> 
> It will works
> 
> @FelixMH

thank you

**Comment by fadiof** [comment]
> Take the content of the file here : https://raw.githubusercontent.com/darkguy2008/parallelshell/master/index.js
> 
> And put the content in your /project/node_modules/parallelshell/index.js
> 
> It will works in waiting the next release of the module

thank you

**Comment by thitlwin** [comment]
> You take the content of this : (100% copy) https://raw.githubusercontent.com/darkguy2008/parallelshell/master/index.js
> 
> And put in your /project/node_modules/parallelshell/index.js (100% paste)
> 
> It will works
> 
> @FelixMH

Thanks. It solves for me too.

**Comment by Shreeharan1207** [comment]
> You take the content of this : (100% copy) https://raw.githubusercontent.com/darkguy2008/parallelshell/master/index.js
> 
> And put in your /project/node_modules/parallelshell/index.js (100% paste)
> 
> It will works
> 
> @FelixMH


Thanks man!

**Comment by flashape** [comment]
~~How is this supposed to work in a ci/cd build environment?~~ Nevermind I only need it to run locally and the fix mentioned above works fine.
